### ISSUE TITLE
[bug]: google and github auth is not working 

### ISSUE THREAD

**Issue by techmannih** [xerocodee/InfraBoard#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello @aryasoni98  
try to  sign up with google and github, on click these button are not working 
I want to solve this issue. assign me

### Steps to reproduce

1.First, check the onclick function.
2.Verify Appwrite authentication with Google or GitHub.
3.Attempt to validate through testing.

### Environment

None

### Version

Local

### Repository

InfraBoard

**Comment by Divesh-Suryavanshi** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current behavior
> Hello @aryasoni98 try to sign up with google and github, on click these button are not working I want to solve this issue. assign me
> 
> ### Steps to reproduce
> 1.First, check the onclick function. 2.Verify Appwrite authentication with Google or GitHub. 3.Attempt to validate through testing.
> 
> ### Environment
> None
> 
> ### Version
> Local
> 
> ### Repository
> InfraBoard

I am not facing any such issue on my local development environment it's working fine, attaching screenshots for reference:-
1. GitHub OAuth
![Screenshot 2024-03-10 141050](https://github.com/xerocodee/InfraBoard/assets/41238260/4da08730-f0e9-4738-87b7-719b3a6ecfcc)

2. Google OAuth
![Screenshot 2024-03-10 141130(2)](https://github.com/xerocodee/InfraBoard/assets/41238260/91d63870-03bc-4f27-b758-9b179b69decf)

Seems like the issue had already been fixed, but the latest changes on master branch are not published yet
![Screenshot 2024-03-10 143934](https://github.com/xerocodee/InfraBoard/assets/41238260/78920154-6d20-42b2-9545-b79db8beb468)
