### ISSUE TITLE
[bug]: Login and Signup is not working 

### ISSUE THREAD

**Issue by techmannih** [xerocodee/InfraBoard#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

facing problem with login and signup 
![Screenshot 2024-02-18 162911](https://github.com/xerocodee/InfraBoard/assets/125847751/81360b01-efa0-497e-b73c-e1a3743795ba)
![Screenshot 2024-02-18 163032](https://github.com/xerocodee/InfraBoard/assets/125847751/06780a23-1bb6-41e7-a879-5a9a2a144fd0)

### Steps to reproduce

1.Verify the functionality of the login and signup processes.
2.Test the login and signup functionalities.

### Environment

None

### Version

Local

### Repository

InfraBoard

**Comment by techmannih** [comment]
@aryasoni98 
 After locally setting up InfraBoard, I noticed that the same error occurred without the environment variable. However, when I tried to start it with the environment variable, it worked well. Please check the deployment; I think there is a mistake in filling the environment variables during deployment

**Comment by aryasoni98** [comment]
@techmannih Check the .env.local

```
NEXT_PUBLIC_APPWRITE_URL = <>
NEXT_PUBLIC_APPWRITE_PROJECT_ID = <>
NEXT_PUBLIC_APPWRITE_DB_ID = <>
NEXT_PUBLIC_APPWRITE_COLLECTION_ID = <>

NEXT_PUBLIC_UCCESS_LOGIN_PATH='http://localhost:3000/'
NEXT_PUBLIC_FAILURE_LOGIN_PATH='http://localhost:3000/login'
```

**Comment by techmannih** [comment]
Yes I m using same as.but I m saying that you have mistake to set the environment variables at the time of deployment because when I m using with environment variables its works well.or when I  m using without environment variables its show same error exactly right row on infraboard'website
