### ISSUE TITLE
[feature]: wrong name of success url environment variables in .env.example

### ISSUE THREAD

**Issue by techmannih** [xerocodee/InfraBoard#63]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Detailed Description

Edit the environment variables name
![Screenshot_20240219_225514_Chrome](https://github.com/xerocodee/InfraBoard/assets/125847751/63817a88-bc61-467c-b5c9-1dc2428656b1)

### Priority/Impact

None

**Comment by aryasoni98** [comment]
@techmannih This is not a feature.
