### ISSUE TITLE
[feature]: Create the Landing Page for InfraBoard

### ISSUE THREAD

**Issue by aryasoni98** [xerocodee/InfraBoard#66]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Detailed Description

The landing page should serve as the entry point to InfraBoard, highlighting its core features and benefits. It should be visually appealing and informative, providing a snapshot of what InfraBoard offers. The design should be intuitive, guiding new visitors to explore the tool's capabilities and encouraging them to try or adopt it for their cloud infrastructure management needs.

### Use Cases and Benefits

- Clearly communicate the value proposition of InfraBoard to first-time visitors.
- Showcase ease of use and efficiency in cloud infrastructure management.
- Increase user engagement by highlighting key features through interactive elements or demos.
- Serve as a marketing tool to boost sign-ups and conversions.

### Priority/Impact

High

**Comment by Avi2492** [comment]
I have seen the design can I start work on this please assign me
