### ISSUE TITLE
[bug]: Hover card overlap to another card 

### ISSUE THREAD

**Issue by aryasoni98** [xerocodee/InfraBoard#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Overlapping hover card card to another canva board nav card. 

### Steps to reproduce

<img width="504" alt="Screenshot 2024-03-11 at 3 54 01 PM" src="https://github.com/xerocodee/InfraBoard/assets/18515597/09adf9bf-7e27-4539-a52a-92c0e2e39d01">

### Environment

Production ( Master Branch )

### Version

Cloud

### Repository

InfraBoard

**Comment by prathameshgaikwad** [comment]
Is this issue resolved?

**Comment by shivajee98** [comment]
@prathameshgaikwad yes
