### ISSUE TITLE
[bug]: The login with google is not working

### ISSUE THREAD

**Issue by Latish705** [xerocodee/InfraBoard#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when I click on the sign in with google it is not working

https://github.com/xerocodee/InfraBoard/assets/104522651/aa399b88-ecef-4ee1-98f0-de5d33d4fd61

### Steps to reproduce

clicking on sign in with google will ask for Google account then after choosing and giving permission it will redirect to login page

### Environment

Production ( Master Branch )

### Version

Local

### Repository

InfraBoard

**Comment by Tomkndn** [comment]
Hey, I want to work on this issue.
Kindly assign me this task under gssoc24. 
Could you please add the level for gssoc.

**Comment by Latish705** [comment]
@aryasoni98 he want to work on this issue

**Comment by Tomkndn** [comment]
I think the bug which is mentioned above doesn't exists.

**Comment by Latish705** [comment]
@Tomkndn still facing the issue

**Comment by Tomkndn** [comment]
The issue was not there, when i evaluated.

**Comment by Latish705** [comment]
can u show us video that it is working

**Comment by Tomkndn** [comment]
just check it out.

https://github.com/xerocodee/InfraBoard/assets/105445488/e6ec689f-0276-4e94-8001-fec8426a52d5
