### ISSUE TITLE
[bug]:Login With Github Issue

### ISSUE THREAD

**Issue by gopalepic** [xerocodee/InfraBoard#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I signup from my Github , and after that I am not able to login , whole page got refreshed 

### Steps to reproduce

Trying by login using any of the ways , either my Google, or try with github 

### Environment

Stage ( Stage Branch )

### Version

Local

### Repository

InfraBoard

**Comment by gopalepic** [comment]
Thank you for assigning me @aryasoni98  , soon coming up with results

**Comment by balaajimuthukumar** [comment]
is this issue fixed? @aryasoni98 @gopalepic
